
version: "3"

services:
  mysql:
    image: mysql:8.0
    platform: linux/amd64
    volumes:
      - /tmp:/tmp
    networks:
      - network
    ports:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: "cmpe172"
    restart: always
  redis:
    image: redis
    networks:
      - network
    ports:
      - 6379:6379
  spring-cashier:
    image: spring-cashier
    platform: linux/amd64
    depends_on:
      - mysql
    volumes:
      - /tmp:/tmp
    networks:
      - network
    ports:
      - 9090
    environment:
      MYSQL_HOST: "mysql"
      REDIS_HOST: "redis"
    restart: always
  lb:
    image: eeacms/haproxy
    platform: linux/amd64
    depends_on:
      - spring-cashier
    ports:
      - "80:5000"
      - "1936:1936"
    environment:
      BACKENDS: "spring-cashier"
      BACKENDS_PORT: "9090"
      DNS_ENABLED: "true"
      COOKIES_ENABLED: "false"
      LOG_LEVEL: "info"
    networks:
      - network

volumes:
  schemas:
    external: false

networks:
  network:
    driver: bridge

